
project_id = "sjzbturfgadikgzokpyo"

[auth]
required_user_fields = ["first_name", "last_name"]
enable_signup = true

[functions]
[functions.handle_new_user]
verify_jwt = true

[functions.auto_confirm_email]
verify_jwt = true

[functions.manually_confirm_email]
verify_jwt = true

[functions.is_email_confirmed]
verify_jwt = true
